# Generated by Django 2.2.4 on 2019-08-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Message', '0001_initial'),
        ('Simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eavesdropper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('eavesdropped_messages', models.ManyToManyField(to='Message.Message')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simulation.Simulation')),
            ],
        ),
    ]
