# Generated by Django 2.2.4 on 2019-08-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.CharField(max_length=100)),
                ('sender_psynm', models.CharField(max_length=100)),
                ('sender_vel', models.FloatField()),
                ('sender_pos', models.CharField(max_length=100)),
                ('sender_angle', models.CharField(max_length=100)),
                ('simTime_sent', models.FloatField()),
                ('simTime_received', models.FloatField()),
                ('simTime_eavesdropped', models.FloatField()),
                ('CPN_readyFlag', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
        ),
    ]
