# Generated by Django 2.2.4 on 2019-08-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_vel',
            new_name='sender_vel_x',
        ),
        migrations.RemoveField(
            model_name='message',
            name='CPN_readyFlag',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_pos',
        ),
        migrations.RemoveField(
            model_name='message',
            name='simTime_received',
        ),
        migrations.RemoveField(
            model_name='message',
            name='simTime_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_pos_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_pos_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_vel_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_angle',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_psynm',
            field=models.IntegerField(),
        ),
    ]
