# Generated by Django 2.2.4 on 2019-08-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('dev_name', models.CharField(max_length=100)),
                ('privacy_scheme', models.CharField(max_length=100)),
            ],
        ),
    ]
